name: testingIfConditions
on:
  workflow_dispatch:
    inputs:
      target_env:
        description: target environment
        type: choice
        default: Stage
        options:
          - Stage
          - Production

jobs:
  build:
    name: build this
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: stage
        if: ${{ github.event.inputs.target_env == 'Stage' }} 
        env:
          ACCOUNT: 1
          REGION: us-west-1
          ACCESS_KEY: a
          SECRET_KEY: aa
        run: |
          echo "${{ env.ACCOUNT }}" >> $GITHUB_ENV
          echo "${{ env.REGION }}" >> $GITHUB_ENV
          echo "${{ env.ACCESS_KEY }}" >> $GITHUB_ENV
          echo "${{ env.SECRET_KEY }}" >> $GITHUB_ENV
      - name: prod
        if: ${{ github.event.inputs.target_env == 'Production' }} 
        env:
          ACCOUNT: 2
          REGION: us-west-2
          ACCESS_KEY: b
          SECRET_KEY: bb
        run: |
          echo "${{ env.ACCOUNT }}" >> $GITHUB_ENV
          echo "${{ env.REGION }}" >> $GITHUB_ENV
          echo "${{ env.ACCESS_KEY }}" >> $GITHUB_ENV
          echo "${{ env.SECRET_KEY }}" >> $GITHUB_ENV
      - name: runthis
        run: |
          echo "run this: ${{ env.ACCOUNT }}"
          echo "run this: ${{ env.REGION }}"
          echo "run this: ${{ env.ACCESS_KEY }}"
          echo "run this: ${{ env.SECRET_KEY }}"
          echo "target env ${{ github.event.inputs.target_env }}"
